.hlint.yaml, README.md, benchmark/CacheMap.hs, benchmark/OptimalVector.hs, benchmark/Vector.hs, internal/Data/TypeRep/CacheMap.hs, internal/Data/TypeRep/OptimalVector.hs, internal/Data/TypeRep/Vector.hs, src/Data/TypeRep/Map.hs, test/Test/TypeRep/CacheMap.hs, test/Test/TypeRep/Vector.hs, test/Test/TypeRep/VectorOpt.hs
=> [#6] Add README, refresh docs, refactor, add hlint

README.md, internal/Data/TypeRep/CacheMap.hs, src/Data/TypeRep/Map.hs, test/Test/TypeRep/MapProperty.hs, typerep-map.cabal
Resolves #17 
Thanks @int-index for idea of this `KindOf` trick!
=> [#17] Add more map-like functions

internal/Data/TypeRep/CacheMap.hs, src/Data/TypeRep/Map.hs
=> [#22] Add 'hoist'

README.md
=> [#27] Add table with benchmark results to README

benchmark/DMap.hs
For some reason we were using `DMap TypeRep Identity` and storing `Identity (Proxy @1)`, `Identity (Proxy @2)`, etc, instead of `DMap TypeRep Proxy` and storing `Proxy @1`, `Proxy @2`, etc, which is what all the other benchmarks were doing.
This `Identity` wrapper could affect performance.
=> Fix the DMap benchmark

.travis.yml, CHANGELOG.md, benchmark/CacheMap.hs, src/Data/TypeRepMap.hs, src/Data/TypeRepMap/Internal.hs, test/Test/TypeRep/CacheMap.hs, test/Test/TypeRep/MapProperty.hs, typerep-map.cabal
=> [#43] IsList instance

CHANGELOG.md, src/Data/TMap.hs, src/Data/TypeRepMap.hs, src/Data/TypeRepMap/Internal.hs
=> [#39] Add hoistWithKey and map for TMap

CHANGELOG.md, src/Data/TMap.hs, src/Data/TypeRepMap.hs, src/Data/TypeRepMap/Internal.hs, typerep-map.cabal
=> [#46] Improve Show instance, add keys

CHANGELOG.md, src/Data/TMap.hs, src/Data/TypeRepMap.hs, src/Data/TypeRepMap/Internal.hs
I'm not sure that I understood the issue correctly. @int-index  could you please confirm that this is what you meant?
Resolves #48
=> [#48] Add adjustWithKey and adjust for TMap

typerep-map.cabal
Hi ! 
Seems like it fits [this issue](https://github.com/kowainik/typerep-map/issues/59) ?
Resolves #59
=> Add bounds to all dependencies

benchmark/DMap.hs, stack.yaml, typerep-map.cabal
=> [#70] Bump dependent-sum to 0.5

.gitignore, stack.yaml, typerep-map.cabal
=> [#75] Bump up to primitive 0.7.0.0

src/Data/TypeRepMap/Internal.hs
=> Fix build on 32 bit platforms

stack.yaml, test/Test.hs, test/Test/TypeRep/CMap.hs, test/Test/TypeRep/TypeRepMap.hs, test/Test/TypeRep/TypeRepMapProperty.hs, test/Test/TypeRep/Vector.hs, test/Test/TypeRep/VectorOpt.hs, typerep-map.cabal
=> [#87] Move tests to hspec

README.md, appveyor.yml
I'm building on both x32 and x64 platforms to make sure that recently implemented changes are valid.
=> Build on Windows CI, update badges

src/Data/TMap.hs, src/Data/TypeRepMap.hs, src/Data/TypeRepMap/Internal.hs, test/Test/TypeRep/TypeRepMapProperty.hs
This would've come in really handy on a recent project I was working on 😄 
Inspired by [alter from Data.Map](https://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Map-Lazy.html#v:alter)
=> Add "alter" combinator

.github/workflows/ci.yml, CHANGELOG.md, README.md
=> [#102] Update default branch to main

src/Data/TypeRepMap.hs
=> Fix Haddock module header formatting

typerep-map.cabal
Things seem to compile fine as-is. The only problem was the bounds.
=> Bumped dependencies to support GHC 9

.github/workflows/ci.yml, CHANGELOG.md, benchmark/CMap.hs, benchmark/CacheMap.hs, benchmark/DMap.hs, src/Data/TypeRepMap/Internal.hs, typerep-map.cabal
=> Support ghc 9.4
